version: '3'

services:
  mariadb:
    image: mariadb:10.1
    ports:
      - "3306:3306"
    volumes:
      - ${PWD}/docker/volumes/mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: Admin1!Admin1!
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: UTC
